### PR TITLE
port to InteractBase / InteractBulma

### PR DESCRIPTION
**Pull request by piever**
This is a WIP PR to port Interact to the new WebIO based frameworks (see [what the new docs would look like](https://piever.github.io/InteractBase.jl/latest/)). This would have three major advantages:

- It works in Blink, Juno and in the browser via Mux, Jupyter notebook and Jupyter lab
- CSS libraries can be added on top of it for styling (it's very easy to change size, color, etc, passing a `style` string or using classes from a given CSS framework) and the layout tools of such CSS framework can be used to create complex UIs. Currently availble frameworks include a pure CSS framework ([Bulma](https://bulma,io)), a CSS+js framework ([UIkit](https://getuikit.com/)) and a material design theme is being worked on.
- Any HTML5 component can be used for widgets, which covers a lot of input types (color, date, time, text, number, range, email, password, autocomplete...) as well as custom features from CSS frameworks (accordions, tabs, etc...)

I feel most functionality is covered already, but I would only want to merge this when the features of the new framework are a superset of the features of the old framework.

Things that would downgrade so far / todo list:

- [x] Missing latex support (I had issues getting katex to work but will try again: [#32](https://github.com/piever/InteractBase.jl/pull/32))

- [x] Missing `textarea` widget (added [here](https://github.com/piever/InteractBase.jl/commit/0560df2aae7d2e303534dcfd868b6fa66a7f9a0e))

- [x] Observables don't display very well in the notebook by default. The user has to do `dom"div"(obs)` to get an observable to display nicely. I could simply add a `text` widget that displays some text and tell the user to do `text(obs)` (it's nice as I could use the typography support of the CSS framework to get it to look nicer)

- [ ] Timer observables are less developed than timer signals, but I'm working on it (see [this PR](https://github.com/JuliaGizmos/Observables.jl)) - not release blocking: it requires some deeper work on `Observable` and garbage collection

- [ ] Somehow it feels that sliders lag a bit in the notebook, not sure why, they are quite responsive in Blink or in atom's plot panel

EDIT: there are two extra things I had missed before

- [x] Interact adds a `label` option to all widgets, whereas I'm afraid I'm not as consistent (fixed by [#26](https://github.com/piever/InteractBase.jl/pull/26))

- [x] I try to use the javascript+html as much as I can and avoid putting Julia listeners unless I have to, which implies that `radiobuttons` and `dropdown` can only have value types that are javascript compatible (say strings or numbers) but not arbitrary Julia types. On the plus side, when this is served remotely, everything can be done client side. Not sure what option is best here (on `togglebuttons` I accept all Julia types, as that's very important to give a good user experience with `@manipulate`) - EDIT: decided to keep the javascript implementation

### CODE REVIEW

**Comment by shashi** [comment]
Whoa! You're quick!

>  Missing latex support (I had issues getting katex to work but will try again)

Happy to help if you need.

>  Missing textarea widget (should be straightforward to add, so far only textbox is available)

Maybe consider a `multiline=true` option to textbox instead?

> Observables don't display very well in the notebook by default.

Maybe we could call WebIO.render on observables by default? This would involve some mild piracy in WebIO where we define HTML `show` for Observables.

>  Somehow it feels that sliders lag a bit in the notebook.

Maybe fire up the chrome profiler?

**Comment by piever** [comment]
> Maybe we could call WebIO.render on observables by default? 

Yes, my preference is to render `Observables` by default. If Interact loads WebIO, I guess that would work without requiring the user to load WebIO.

>> Missing latex support (I had issues getting katex to work but will try again)
>
> Happy to help if you need.

Actually I could use some help on this one. I've tried to use the snippet from [InteractNext](https://github.com/JuliaGizmos/InteractNext.jl/blob/master/src/output_widgets.jl) but it does not work on my machine. From what I understood I would need to call `katex.render` on the widget somehow but if I do:

```julia
    onimport(tex, js"""
        function (katex) {
            return katex.render($(formula[]), document.getElementById(...));
        }
        """)
```

I get an error that `katex` is not defined. I'm not 100% sure that I completely understand `onimport` though, so I may be doing something silly.

**Comment by shashi** [comment]
screenshot from 2018-06-02 19-10-01
Seems to work for me. Maybe try a different version of Katex? (this one is alpha :sweat_smile: )

**Comment by piever** [comment]
> Maybe consider a `multiline=true` option to `textbox` instead?

I like `textarea` because it is the HTML name, so I would keep it (it is a proper tag rather than a type of the input tag), but `textbox(args...; multiline = true)` can definitely call `textarea`.

**Comment by piever** [comment]
As a "teaser" of the new features with the InteractBase port, this is the `colorpicker` integrated in the `@manipulate` macro:

interact

**Comment by shashi** [comment]
Looking good!

**Comment by piever** [comment]
I'm not too far. Could you look into [#11](https://github.com/JuliaGizmos/Observables.jl/pull/11) and see if there are more timing `Observables` we could add? I've opened [#133](https://github.com/JuliaGizmos/WebIO.jl/issues/133) to discuss `Observable` rendering. Other than that I think this is almost ready.

**Comment by shashi** [comment]
I see you have updated the OP after our discussion about Observables `#11`. :+1:

I think I can live with Dropdowns etc only supporting basic types... When someone adds a Julia listener, they can maybe convert it.

**Comment by piever** [comment]
I thought so too, I think it's important to give the option of avoiding unnecessary listeners. Then I think I only need to finish updating the notebooks, tag a release of InteractBase/Bulma/UIkit and this should be good to go.

The last notebooks has some complex examples of vectorial animations with `Compose`. I replicated the first with `dom"svg"`, for the rest I though I could put some more "scientific computing" like example: like a differential equation being solved in real time with some sliders to manipulate as parameters.

**Comment by shashi** [comment]
Okay those new examples sound good!

**Comment by shashi** [comment]
Did you mean to delete the notebooks..? I was thinking you'll check in the new updated notebooks in their place.

**Comment by piever** [comment]
I think GitHub is not doing a spectacular job at showing the diff, but the notebooks have not been deleted, I've simply updated them (the diff is largely negative as I always do "clear output" before saving). You can find them [here](https://github.com/piever/Interact.jl/tree/interactbase/doc/notebooks) in my branch.

**Comment by shashi** [comment]
Oh I see, my bad. Yes, it actually just looks like the file got deleted since I didn't know what the gray box at the end means.

**Pull request merged**
