### PR TITLE
Adds hbox and vbox

### LINKED ISSUE #48: Layout Options for Widgets
Is there any way to control where widgets will appear when displaying more than one of them? E.g. say I wanted to have multiple checkboxes side by side. They seem to stack vertically by default. Something like hstack in Gadfly would be great. I guess this is somewhat related to https://github.com/JuliaLang/Interact.jl/issues/38 which I also would very much like to see. 

Would be happy to have a bash at it but not sure really where to start.

Ta!

### PR DESCRIPTION
**Pull request by JobJob**
create_view factored to create the comm, but not send the "method"=>"display" message. display_widget does that now after calling create_view.

Bonus: slightly raw Dev Guide

Fixes #48 😄

### CODE REVIEW

**Comment by shashi** [comment]
Awesome. :tada:

**Comment by shashi** [comment]
Is there a way of setting margins / paddings / width / height of the hbox and vboxes?
Have you thought about how we can add this to the `@manipulate` syntax?

**Comment by JobJob** [comment]
> Is there a way of setting margins / paddings / width / height of the hbox and vboxes?
Yes it can be done, but it's not implemented yet, probably shouldn't be too hard.

> Have you thought about how we can add this to the @manipulate syntax?
Hmmm... no, gonna be a bit fiddly. Ideas:
```
@manipulate for layout in hbox(i in 1:10, j in 2:10)
#or
@manipulate for i in 1:10, j in 2:10, layout in hbox(i,j)
```

**Comment by shashi** [comment]
I like the second one better - it's easier to understand and probably to implement... We can probably reserve `layout` for this, or use something like `layout(hbox(i,j))` or `@layout hbox(i,j)` instead.

**Comment by JobJob** [comment]
👍

**Pull request merged**
